config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :tasks
  end
  root "projects#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  belongs_to :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @project = Project.all.order("created_at DESC")
  end

  def show
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(project_params)

    if @project.save
      redirect_to @project, notice: "Successfully created new project"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path, notice: "Successfully deleted project"
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end

  def find_project
    @project = Project.find(params[:id])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html></html>
<head>
  <title>Projects</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "All Projects", root_path, class: "btn btn-primary" %>
      </div>
      <div>
        <ul class="navbar-text navbar-right">
            <% if user_signed_in? %>
  							<%= link_to "New Project", new_project_path, class: "btn btn-default" %>
  							<%= link_to 'Account', edit_user_registration_path, class: "btn btn-default" %>
  							<%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: "btn btn-default"%>
  					<% else -%>
  							<%= link_to 'Sign up', new_user_registration_path, class: "btn btn-default" %>
  							<%= link_to 'Sign in', new_user_session_path, class: "btn btn-default" %>
  					<% end -%>
        </ul>
      </div>

    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert" %>
    <% end %>

    <%= yield %>

  </div>
</body>

app/views/projects/_form.html.erb
<%= simple_form_for @project, html: { multipart: true } do |f| %>
  <% if @project.errors.any? %>
    <div id="errors">
      <p>
        <%= @project.errors.counat %>
        Prevented this project froms saving
      </p>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-body">
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= render 'form' %>

app/views/projects/index.html.erb
<% @project.each do |project| %>
  <h2><%= link_to project.title, project %></h2>
  <p>
    Сreated at <%= project.created_at.strftime('%b %d, %Y') %>
		by<%= project.user.email %>
  </p>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>
<br/>
<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<p><%= @project.description %></p>

<%= link_to "Back", root_path, class: "btn btn-default" %>
<%= link_to "Edit", edit_project_path, class: "btn btn-default" %>
<%= link_to "Delete", project_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default" %>